CREATE TABLE `IPAddress` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ListID` int(11) NOT NULL,
  `Address` VARBINARY(16) NOT NULL,
  `Network` TINYINT(4) DEFAULT NULL,
  `Comment` VARCHAR(255) DEFAULT NULL,
  `Created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_IPAddress_List` (`ListID`,`Address`,`Network`),
  KEY `IX_IPAddress_Parts` (`Part1`,`Part2`,`Part3`,`Part4`,`Part5`,`Part6`,`Part7`,`Part8`,`Network`),
  KEY `fk_IPAddress_List_idx` (`ListID`),
  CONSTRAINT `fk_IPAddress_List` FOREIGN KEY (`ListID`) REFERENCES `List` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;
